### PR TITLE
ureadahead: fix memory corruption in add_inodes

### PR DESCRIPTION
**Pull request by nullpo-head**
Maybe this PR should be cherry-picked instead of being merged.

Steven made [the update branch](https://github.com/rostedt/ureadahead/tree/update) and I tested on Debian and ChromeOS, but there is a probabilistic memory corruption bug. This commit fixes that and unblock the update branch

### CODE REVIEW

**Review by rostedt — COMMENTED** [review]
This is why we need to get rid of libnih!

**Comment by computersforpeace** [comment]
Doesn't a `NULL` parent mean `trace_add_path` might leak memory?

I'd say this is more of an argument to get rid of C, BTW :wink: Application code in C is way more likely to have memory leaks (and tons of other problems) without some kind of object helper library.

**Comment by rostedt** [comment]
Yeah, it probably does, but honestly, ureadahead is not something to be running for a long time, and all memory leaks will be cleaned up on exit. Now that's not condoning memory leaks. Yes C is likely to have leaks, but tooling like valgrind helps remove them. This is really more of an issue of using a nonstandard library for basic functionality like allocation.

**Comment by computersforpeace** [comment]
Re nonstandard: you could say the same about the kernel's kmalloc (and devm
variants, and ...), probably. But the kernel project just expects people to
use the APIs properly (and learn gfp flags, device structs, ...). I think
the answer is the same here.

Anyway, the NIH name is cute, and does make you think...

**Comment by rostedt** [comment]
Well, in the kernel, there is no libraries. Everything must be created from scratch. You can't use glibc's malloc, or even printf. Not quite the same at all. For user space, there's no reason to recreate the wheel.

**Comment by computersforpeace** [comment]
Sure, the kernel can have libraries! They just tend to need to be statically linked. Today, the kernel tends to vendor copies of the libraries it wants (e.g., compression, crypto), but it doesn't have to.

Anyway, this question is not about the precise library implementation, but about (unfamiliar) APIs. There's no real reason the kernel couldn't implement `void *malloc(size_t)`.

**Comment by rostedt** [comment]
What do you mean it can have libraries? Statically linked isn't the issue. Libraries do system calls to get what it needs. Where do you think those system calls go? In the kernel. Even malloc() needs to get memory somewhere. Yes, the kernel could do system calls (in some cases it does), but it's very inefficient and requires a great deal of care. Now, if Linux was a maco-kernel and not a monolithic one, then that may be possible. But that debate has already been done.

The reason the kernel doesn't do `void *malloc(size_t)` is because the allocation needs to know what context the kernel is in when it requests memory. That's what those GFP flags are for. To let the allocator know how it can acquire that memory.  As you know, the kernel aggressively tries to use memory for all sorts of caching. Memory is seldom unused. To acquire new memory, it needs to free some of the cache. That freeing takes locks and may even require scheduling. If the kernel is in a non sleepable state (which user space never has to worry about) the allocator must not do something that sleeps. If the allocation happens while doing something in the file system where file system locks are held, putting memory back onto disk can cause a deadlock and the allocator needs to know about that too.

I do not accept the argument that the kernel malloc() can simply use a user space library version.

**Comment by computersforpeace** [comment]
> I do not accept the argument that the kernel malloc() can simply use a user space library version.

I never said user space. You've put lots of words in my mouth, and missed my point entirely. Anyway, it doesn't really matter.

**Comment by rostedt** [comment]
Sorry, that's what I think of when I hear "libraries". But you are correct. This discussion has nothing to do with the commit.

**Comment by nullpo-head** [comment]
As for this part,

> Doesn't a NULL parent mean trace_add_path might leak memory?

Actually no. `trace` also frees the final `PackFile` data structure (`nih_local PackFilie *files`) in addition to the nih's automatic refcount, so there's no memory leak.

**Comment by computersforpeace** [comment]
> `trace` also frees the final `PackFile` data structure (`nih_local PackFilie *files`) in addition to the nih's automatic refcount, so there's no memory leak.

Good note. So the only problem is any future code that might assume the libnih-style `parent` will actually perform reference counting. I guess that's a problem for future programmers, if they exist.

**Comment by rostedt** [comment]
The next future change is to remove the dependency on libnih ;-)

**Comment by nullpo-head** [comment]
it's merged to `update` branch

**Pull request closed without merging**
